version: '3'
services:
  mongo_db:
    image: mongo:3.6
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    restart: always
    environment:
        MONGO_INITDB_DATABASE: MEANStackDB
volumes:
  mongodb:
