aws_region      = "us-west-2"
aws_cli_profile = "develop_poc"
dynamodb   = "state-poc" 
s3_bucket_logs = "dev-bucket-logs-7423"   
s3_bucket_state = "dev-bucket-state"   
#repo   = "doswaldo7423/app-easytrack-ionic-cdci"  
repo_front   = "@dsierra74/smartydreams/ar/platform_v1/project_apps/campaigns"

repo_back   = "dsierra7423/MEAN-Stack-User-Registration---Back-End"
branch = "main"
account_id = "259941133233"
pipeline_assume_role =  "arn:aws:iam::259941133233:role/IaC"